// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.Sql.CreateNewDataBase")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.Sql.ExecuteRead(System.String,System.Collections.Generic.Dictionary{System.String,System.Object})~System.Data.DataTable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.Sql.ExecuteRead(System.String)~System.Data.DataTable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.Sql.ExecuteWrite(System.String,System.Collections.Generic.Dictionary{System.String,System.Object})~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.MainWindow.Cal_DataGrid_SelectionChanged(System.Object,System.Windows.Controls.SelectionChangedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.MainWindow.BlackOutCalenderDays(System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.MainWindow.Cal_Button_UpdateServiceTimeSpan_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.MainWindow.Cal_Button_CreateServiceTimeSpan_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.MainWindow.CreateNewServiceWeek")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.Sql.ExecuteWrite(System.String,System.Collections.Generic.Dictionary{System.String,System.Object})~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~P:MelBox2_2.Gsm.PortName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.Gsm.OpenPort(System.String)~System.IO.Ports.SerialPort")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.MainWindow.OpenPort(System.String)~System.IO.Ports.SerialPort")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Ausstehend>", Scope = "member", Target = "~M:MelBox2_2.MainWindow.ExecCommand(System.String,System.Int32,System.String)~System.String")]
